"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['Clock.py']
DATA_FILES = ["./resources"]
OPTIONS = {
  'iconfile':'icon.icns',
}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
    plist={
      "CFBundleGetInfoString": "A Rain World Clock",
      "CFBundleIdentifier": "org.trebor-huang.rainworldclock",
      "LSUIElement": True
    }
)
